package com.mycompany.hospedagempets.view;

import com.mycompany.hospedagempets.model.ServicoAdicional;
import com.mycompany.hospedagempets.model.TipoAcomodacao;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class HospedagemView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HospedagemView.class.getName());

    /**
     * Creates new form HospedagemView
     */
    public HospedagemView() {
        initComponents();
        
        for(TipoAcomodacao acomodacao : TipoAcomodacao.values()) {
            cmbAcomodacao.addItem(acomodacao);
        }
                
    }
    
    public void adicionarListenerCadastrar(ActionListener listener) {
            btnCadastrar.addActionListener(listener);
        }

    public String getNomeAnimal() {
        return txtNomeAnimal.getText();
    }
    
    public String getNomeResponsavel() {
        return txtNomeResponsavel.getText();
    }
    
    public Integer getQtdDiarias() {
        return (Integer)spnDiarias.getValue();
    }
    
    public String getEspecie() {
        String especie;
        if (rdbCachorro.isSelected()) {
            especie = "Cachorro";
            return especie;
        }
        if(rdbGato.isSelected()) {
            especie = "Gato";
            return especie;
        }
        return null;
    }
    
    public TipoAcomodacao getTipoAcomodacao() {
        return (TipoAcomodacao)cmbAcomodacao.getSelectedItem();
    }
    
    public List<ServicoAdicional> getServicos() {
        List<ServicoAdicional> lista = new ArrayList<>();
        
        if (chkBanho.isSelected()) {
            lista.add(ServicoAdicional.BANHO);
        }
        
        if(chkTosa.isSelected()) {
            lista.add(ServicoAdicional.TOSA);
        }
        
        if(chkPasseio.isSelected()) {
            lista.add(ServicoAdicional.PASSEIO);
        }
        
        if(chkAcompVeterinario.isSelected()) {
            lista.add(ServicoAdicional.ACOMPANHAMENTO_VETERINARIO);
        }
        
        return lista;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoEspecie = new javax.swing.ButtonGroup();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtNomeAnimal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeResponsavel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spnDiarias = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        rdbCachorro = new javax.swing.JRadioButton();
        rdbGato = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cmbAcomodacao = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        chkBanho = new javax.swing.JCheckBox();
        chkTosa = new javax.swing.JCheckBox();
        chkAcompVeterinario = new javax.swing.JCheckBox();
        chkPasseio = new javax.swing.JCheckBox();
        btnCadastrar = new javax.swing.JButton();

        jCheckBox3.setText("jCheckBox3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome do Animal:");

        jLabel2.setText("Responsavel:");

        txtNomeResponsavel.addActionListener(this::txtNomeResponsavelActionPerformed);

        jLabel3.setText("Qtd. Diárias:");

        spnDiarias.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setText("Especie do Animal:");

        btnGrupoEspecie.add(rdbCachorro);
        rdbCachorro.setText("Cachorro");

        btnGrupoEspecie.add(rdbGato);
        rdbGato.setText("Gato");

        jLabel5.setText("Tipo de Acomodação:");

        jLabel6.setText("Servicos Adicionais:");

        chkBanho.setText("Banho");

        chkTosa.setText("Tosa");

        chkAcompVeterinario.setText("Acomp. Veterinário");

        chkPasseio.setText("Passeio");

        btnCadastrar.setText("Cadastrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtNomeAnimal)
                            .addComponent(spnDiarias)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbCachorro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbGato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkBanho)
                            .addComponent(chkTosa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAcompVeterinario)
                            .addComponent(chkPasseio))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnDiarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdbCachorro)
                    .addComponent(rdbGato))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chkBanho)
                    .addComponent(chkPasseio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAcompVeterinario)
                    .addComponent(chkTosa))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeResponsavelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HospedagemView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup btnGrupoEspecie;
    private javax.swing.JCheckBox chkAcompVeterinario;
    private javax.swing.JCheckBox chkBanho;
    private javax.swing.JCheckBox chkPasseio;
    private javax.swing.JCheckBox chkTosa;
    private javax.swing.JComboBox<TipoAcomodacao> cmbAcomodacao;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rdbCachorro;
    private javax.swing.JRadioButton rdbGato;
    private javax.swing.JSpinner spnDiarias;
    private javax.swing.JTextField txtNomeAnimal;
    private javax.swing.JTextField txtNomeResponsavel;
    // End of variables declaration//GEN-END:variables
}
